# POST http://localhost:3000/publish-blog 
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTM0YjcwMTcwNDJiZWRjNzBiYzUzMCIsImlhdCI6MTcxNjczNDgzMn0.X_YeK2OPFpYD9SwIyzQyc9ule-RS6lIytxiJQD3yw8E

# {

#  "blog_title":"helo",
#  "blog_banner_img_url":"dqvg",
#  "blog_content":{
#     "blocks":[1,2,3]
#  },
#  "blog_tags":["haii","bye"],
#  "blog_des":"avuvys"
# }

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTMxNzIwNTllZGEyZWNmMjFmNGUyOSIsImlhdCI6MTcxNjcyMTQ5M30.sDrC3UPaBzMJMa3PGNy2ICwipGVo0vWcdjB5alPbVCY
# POST http://localhost:3000/signin 
# Content-Type: application/json

# {
# "email": "bibinbabumj10@gmai.com",
#  "password": "@Niravu85839"
# }


# GET http://localhost:3000/get-upload-url 

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTM1NTRiY2JlMGJmNGVhNzFmNzI2ZCIsImlhdCI6MTcxNjczNzM1NX0.udeVAE0rWY4gRq_hm0jfSnVVrYgzXf1Y5ATtk9LJaJs

POST http://localhost:3000/signup 
Content-Type: application/json

{
"email": "bibinbabumj93@gmai.com",
"fullname":"bibin babu",
 "password": "@Niravu85839"
}